// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9o9PuUHshwFHdhyHDn5WwDnbZi3iR87w',
    appId: '1:288562079657:web:41f9748849127d1f4806b8',
    messagingSenderId: '288562079657',
    projectId: 'wedring-96848',
    authDomain: 'wedring-96848.firebaseapp.com',
    storageBucket: 'wedring-96848.appspot.com',
    measurementId: 'G-LRLEP8STM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8SHyRBMlHCFvV_G0E3ReEDLWvDOYZEP4',
    appId: '1:288562079657:android:849a70eaeecd42c34806b8',
    messagingSenderId: '288562079657',
    projectId: 'wedring-96848',
    storageBucket: 'wedring-96848.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI0CNTBZfyww2-X9wLdy-ZyzAWvBbP_Vo',
    appId: '1:288562079657:ios:e4637a0e6267d65d4806b8',
    messagingSenderId: '288562079657',
    projectId: 'wedring-96848',
    storageBucket: 'wedring-96848.appspot.com',
    iosClientId: '288562079657-lnrmdt5hinb66q53l1r50sq78u8826dc.apps.googleusercontent.com',
    iosBundleId: 'com.example.wedring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI0CNTBZfyww2-X9wLdy-ZyzAWvBbP_Vo',
    appId: '1:288562079657:ios:43e6ed5f975e25364806b8',
    messagingSenderId: '288562079657',
    projectId: 'wedring-96848',
    storageBucket: 'wedring-96848.appspot.com',
    iosClientId: '288562079657-mi6a5p8peqj27rinom0baj8lucqs0gam.apps.googleusercontent.com',
    iosBundleId: 'com.example.wedring.RunnerTests',
  );
}
